backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Image", name: "image", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Image", name: "image", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Products"
        name: "products"
        folder: "content/products"
        create: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Price", name: "price", widget: "number" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Featured", name: "featured", widget: "boolean" }
          - { label: "Tags", name: "tags", widget: "list" }
          - {
              label: "Categories",
              name: "categories",
              widget: "relation",
              collection: "categories",
              multiple: true,
            }
